// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("ELECTRICIDAD.html", "Untitled Page", "NUEVAS OFERTAS  TOMA E INTERRUPTOR  Toma corriente marca Aguila  Interruptor marca Aguila  Toma corriente marca Bticino  Interruptor doble marca Bticino  Interruptor simple marca Bticino  Protector de voltaje  ILUMINACION  Angel light bombillo led 9w  Multimetro digital con tension total tmt46001  BOMBILLO LED 9W  BOMBILLO LED ALTA POTENCIA ANGEL LIGHT 80W  Bombillo Led Luz blanca  Bombillo led 40w e27 6500k t120 blco  Volteck led 75W  Volteck kids  Multimetro digital con tension total tmt46001  OTROS  Multimetro digital con tension total tmt42002  Multimetro digital con tension total tmt46001  Guante de nitrilo Total  Guantes de carnaza y loneta Truper   Foco De Mano Pretul Recargable    Linterna Led De 15 Leds Recargable    ", "");
   this[database_length++] = new SearchPage("CONSTRUCCION.html", "Untitled Page", "         MATERIALES DE CONSTRUCCION  EN CONSTRUCCIÓN, SOMOS TU MEJOR OPCIÓN    CADA MATERIAL CUENTA   Tornillos para tabla yeso  Tornillo Para Tabla Yeso Punta Fina #6 x 3 Plg  Tornillo Para Tabla Yeso Punta Fina #6 x 3 Plg   Clavo De Acero De 4 y 5 Pulgadas  Tornillo Para Tabla Yeso Punta Fina #6 x 3 Plg  Tornillo Para Tabla Yeso Punta Fina #6 x 2 Plg    ", "");
   this[database_length++] = new SearchPage("PISOS.html", "Untitled Page", "PISOS Y REVESTIMIENTOS  Pegamix Cemix  Super Pulido Toro  Piso Sobre Piso de Cemix  Piso Sobre Piso Gris de Pegadura  Súper Pulido  Súper Capa  SOMOS TU MEJOR OPCIÓN EN CERÁMICAS   ", "");
   this[database_length++] = new SearchPage("Mas.html", "Untitled Page", "AGRO DIFEMAFER   ", "");
   this[database_length++] = new SearchPage("HERRAMIENTAS.html", "Untitled Page", "       HERRAMIENTAS  TOTAL  Equipo para pintar TT3506  Taladro Percutor TG111136  Cepillo Eléctrico TL1108236  Total Welding Goggles   Equipo para pintar TT5006  Amoladora Angular TG1121256  Amoladora Angular TG1302306  Taladro Percutor 20V – TIDLI2003-4  Hidrolavadora – TGT11316  Amoladora Angular TG1302306  Pinzas Alicate  Destornilladores Plano  Tijera Corta Tubos de PVC  Destornilladores Philips  TRUPER  Sierra Circular  Rotomartillo  Taladro Truper 1/2 Roto-1/2a8  Pistola Para Pintar Electrica 330  CEPILLO TRUPER CH-7 CARPINTERO   Manguera Para Compresor   Cortador de azulejo  Flexometro Gripper Resiste Impactos  INYECTOR DE GRASA   Cinta Métrica 8 Metros  TOLSEN  Automatic welding mask  Oil Can  Guantes anticorte  PRETUL  Juego de herramientas  Foco de mano recargable  PISTOLA PLÁSTICA P/RIEGO   ", "");
   this[database_length++] = new SearchPage("HOGAR.html", "Untitled Page", "         ACCESORIOS PARA EL HOGAR  CERRAJERIA  CH-38X4 BLISTER CON 4 CANDADOS DE HIERRO DE 38M  Candados de seguridad Hermex  Candado Hermex 65mm Ca-65lq Acero Redondo Gancho Largo  CANDADO ACERO 50 mm CUBIERTA PVC HERMEXDE HIERRO DE 38M  Pasador Dorado Porta Candado De 4 Plg Boxer  Aldaba de Cerradura  Ficha Tecnica Broquero de 3/8\" con llave  Cerradura de sobreponer derecha  Aldaba de Cerradura  Phillips Cerradura Para Puerta Corrediza  Candado Hermex Basic    Perillas de paso de bola plateada  Phillips Pasador De 2-1/2 Plg Boxer  TU COCINA  Black and Decker cafetera   Mini dispensador de agua  Escurridor de vajilla  ESTUFA DE MESA DE 2Q ECOCINA  ESTUFA DE MESA DE 3Q ECOCINA   Balanza con plato  Cuchilla Picahielo Oster  IML CERO FUGAS  Ficha Tecnica Dispensador eléctrico de agua  MASCOTAS  Hueso de goma  Hueso blanco cuero  Hueso de goma con correa  Aro de goma con correa  Cuerda con pelota  Pelota para perro  Juguete palo de hule  Collar perro huellitas  Correa huesitos  OTROS  Ventilador Mastercraft  Escaleras  Escaleras Cuprum  Maceta plástica tipo rattán  Maceta plástica terracotta distintas formas   Rastrillo Plastico De 26 Dientes Rotter  Pala de Jardineria   Conjunto para jardinería Tramontina  AUTOS  CASTROL GTX 10W-30   Pala de Jardineria   Aceite de Motor 15W40   Quaker State Aceite de Motor   CASTROL® 15W-40 CRB TURBOMAX  Dot 3 Brake Fluid - ABRO  ABRO Coolant para Radiador 1 L  MOTUL 3000 20W-50 4T - Motul  Aceite CASTROL ACTEVO 4T 20W-50   URSA® HD SAE 40, 50   Lubricantes Chevron  Engine Coolant Green   Super S no detergente sae 50 aceite de motor  Power Steering Fluid  2-Cycle Engine Oil  Abro Motor Oil SA SAE 50   ", "");
   this[database_length++] = new SearchPage("PRINCIPAL.html", "Untitled Page", "La misión de nuestra ferretería es proporcionar herramientas y materiales de alta calidad con un excelente servicio al cliente, facilitando soluciones prácticas para proyectos de construcción, reparación y mejoras en el hogar Nos comprometemos a ofrecer asesoramiento experto y a mantener una amplia gama de productos que satisfagan las necesidades de nuestros clientes  Nuestra visión es ser la ferretería de referencia en nuestra comunidad, reconocida por nuestra capacidad de innovación, la excelencia en el servicio y la confianza que generamos en nuestros clientes Buscamos expandirnos y adaptarnos a las nuevas tendencias del mercado, siempre con un enfoque en la sostenibilidad y la satisfacción total del cliente  En Difemafer, tu ferretería de confianza, nos dedicamos a ofrecer productos de alta calidad y un servicio excepcional Ubicados en el corazón de la comunidad, brindamos herramientas y materiales para profesionales y aficionados al bricolaje Nuestro equipo está listo para asesorarte y garantizar que encuentres lo que necesitas Agradecemos tu confianza y estamos aquí para ayudarte a construir tus sueños   ", "");
   this[database_length++] = new SearchPage("FONTANERIA.html", "Untitled Page", "            FONTANERIA  Tuberia PVC  Camiseta de tubo PVC  Codo PVC  CAMISA RHINOCERONTE/ALFA  UNION   ADAPTADOR HEMBRA  REDUCTOR RHINOCERONTE  SILICONA GREY 999   Truper SIL-85BCB, Sellador blanco para baño y cocina  Silicon Negro Abro De 3 Onz   Silicon Transparente 80ml   Epoxy Clear 1 oz  PEGAMENTO EPOXICO   Adhesivo de resistencia Alta para pernos de 3/8'  Adhesivo Epóxico Loctite 98g  SILICON ABRO TRANS.300ML  Acrylic Latex  LANCO PISTOLA MASILLA REFORZADA GRIS   ABRO Grease NLGI 1   Valvula BañO 1/2 Perilla Acrilico  Llave Para Regadera Tipo Palanca  Llave sencilla para lavamanos  Ducha octagonal con brazo y chapeta  Cabeza para ducha redonda  Sanitario Powermax blanco   Anillo de cera para inodoro  Inodoro Milán  REPOSADERA CUADRADA  Lavatrasto Foset 800x500 Mm  Foset Aqua AQM-51, Mezcladora para lavabo  Valvula Baño foset   ", "");
   this[database_length++] = new SearchPage("CONTACTO.html", "Untitled Page", "CONTACTO  Ubicación  Barrio San Cayetano, media cuadra adelante de la iglesia Católica, San Nicolás, Copán  agrodifemafer17@gmail.com   Tel 3341-0972   ", "");
   return this;
}
